kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: hello-world-scaler
  namespace: hpa-demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: hello-world-java
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: External
    external:
      metricName: hello-world-throughput
      targetAverageValue: 60
